### ISSUE TITLE
Don't replace native JS object like Date with ui5 sap/ui/model/type/Date

### ISSUE THREAD

**Issue by NoelHendrikx** [SAP/ui5-migration#10]
After migration the new Date() (native js) will be replaced with sap/ui/model/type/Date.

This should not be the case :)

All native datetime objects are not working anymore. By removing the define and parameter, the code works again.

**Comment by petermuessig** [comment]
Thanks for providing feedback again. We will take a look into this issue. This should definitely not be the case... :-)

**Comment by petermuessig** [comment]
BTW: does it just happen when adding the new Date()

**Comment by petermuessig** [comment]
I tried to reproduce it by adding new Date() to some piece of code and run the ui5-migration but on my side the Date has not been migrated. Can you please share an example to reproduce it with us? THX.

**Comment by codeworrior** [comment]
Was indeed the use of `Date` the trigger for a replacement? I hope not. I guess there was a `sap.ui.model.type.Date` used anywhere, the tool added a dependency to it and was not careful when picking a name for the import parameter? So the local parameter `Date` was hiding the global `Date` class.

At least I've seen such issues in the past. But I thought the [`VariableNameCreator`](https://github.com/SAP/ui5-migration/blob/master/src/util/VariableNameCreator.ts) meanwhile would prevent this. Seems, it doesn't.

**Comment by NoelHendrikx** [comment]
Searching my repo now to provide some feedback and finally found it :)

sap.ui.model.type.Date was also in the code, so the tool added the define and replacement to Date.

This could easily be solved with a different name like modelDate. This would not replace the new Date() functions :)

**Comment by petermuessig** [comment]
That's what I thought, but didn't try. Let's see what's possible - I will take a look soon...

**Comment by tobiasso85** [comment]
sample:
original:
```js
sap.ui.define([], function() {
  "use strict";
  var result = new sap.ui.model.type.Date();
});
```

modified:
```js
sap.ui.define(["sap/ui/model/type/Date"], function(Date) {
  "use strict";
  var result = new Date();
});
```

**Comment by codeworrior** [comment]
which alone would be fine, wouldn't it? It only becomes a problem when the name `Date` was already used before:

original:
```js
sap.ui.define([], function() {
  "use strict";
  var result = new sap.ui.model.type.Date();
  console.log(new Date());
});
```

after:
```js
sap.ui.define(["sap/ui/model/type/Date"], function(Date) {
  "use strict";
  var result = new sap.ui.model.type.Date();
  console.log(new Date()); // dumps a new instance of the Date model type to the console
});
```

And this is totally independent from `Date`. I would assume that any already used global name might cause the same problem:

original:
```js
sap.ui.define([], function() {
  "use strict";
  var result = new sap.ui.core.Element();
  console.log(Element.ELEMENT_NODE);  // writes "1" to the console
});
```

after:
```js
sap.ui.define(["sap/ui/core/Element"], function(Element) {
  "use strict";
  var result = new Element();
  console.log(Element.ELEMENT_NODE); // now writes undefined to the console
});
```
