### ISSUE TITLE
Can't install ui5-migrate

### ISSUE THREAD

**Issue by NoelHendrikx** [SAP/ui5-migration#3]
I tried to npm install ui5-migration --global, but npm reports:
npm ERR! code E404
npm ERR! 404 Not Found: ui5-migration@latest

Also npm install --global @ui5/migration responds with a:
npm ERR! code E404
npm ERR! 404 Not Found: @ui5/migration@latest

**Comment by petermuessig** [comment]
Hi Noel,

there is an issue currently in the documentation after we renamed the module using the @ui5 scope. We will update the documentation soon with the following pull request: https://github.com/SAP/ui5-migration/pull/2.

Regarding the release to the NPM registry, we are about to prepare this. For the time being, please use linking locally to use it.

It would be great to get feedback on the tooling. We will initially collect and consolidate all feedback to plan the next iteration of the migration tools.

Thanks and best regards,
Peter

**Comment by NoelHendrikx** [comment]
Hi Peter,

How do I link it locally? By cloning the repo into my workspace (node_modules folder)?

Cheers,

Noël

**Comment by petermuessig** [comment]
Hi Noël,

just run:

```cli
npm i
npm link
```

This should link the global executable ui5-migration to this project.

HTH and BR,
Peter

**Comment by NoelHendrikx** [comment]
After cloning this repo I ran npm i and npm link in the cloned repository.

In my ui5 project I added a task in the package.json:
`    "migrate": "ui5-migration migrate",`

And ran npm migrate :-)

8 files changed, deep diving into the results now 👍
