### ISSUE TITLE
Chain operator causing issue while running migration tool

### ISSUE THREAD

**Issue by DashrathSinghSAP** [SAP/ui5-migration#316]
When we have chain operator in the code, we can't use that file for migration. It starts throwing error until we remove chain operator to old way of working.
Eg: oResponse && oResponse.prop1 will work but oResponse?.prop1 doesn't.

**Comment by flovogt** [comment]
Hi @DashrathSinghSAP,
the current version of [`ui5-migration`](https://www.npmjs.com/package/@ui5/migration) does not support newer ECMAScript language features than ES2017 and it is also not planned to implement any new functionality.

The future linting tool for UI5 projects is [ui5-linter](https://github.com/SAP/ui5-linter). Currently, this tool does not offer an actual migration but report findings, so you can easily fix it on your own.
