### ISSUE TITLE
'migrate' removes line break(s) at the end of a file

### ISSUE THREAD

**Issue by codeworrior** [SAP/ui5-migration#35]
While working on https://github.com/SAP/openui5/commit/c782ce9be8cbd71201e19ba3cb4c0e81e439b71f , I encountered the following issue with the ui5-migration tooling:

In files that are not touched otherwise, line feeds at the end are removed. While this doesn'T cause build or runtime issues, it creates a lot of noise in changes and the only workaround seems to be to revert those changes manually, which is cumbersome.

To reproduce, you can execute the following commands

```
cd openui5
git checkout 6555a38
ui5-migration migrate src/sap.ui.core/src/sap/ui/dom/jquery
```

**Comment by tobiasso85** [comment]
simplified example

**before**
```js
sap.ui.define(['sap/ui/thirdparty/jquery'], function(jQuery) {
	"use strict";

	return jQuery("a");

});


```

**after:**
```js
sap.ui.define(['sap/ui/thirdparty/jquery'], function(jQuery) {
	"use strict";

	return jQuery("a");

});
```
