### ISSUE TITLE
'migrate', tool uses an incorrect replacement for the UriParameter

### ISSUE THREAD

**Issue by StSche** [SAP/ui5-migration#66]
The following replacement is done by the migration tool:
„jQuery.sap.getUriParameters().get("$direct")“ by “new UriParameters(window.location.href).get("$direct")”
But in the JSDoc of the UriParameter is described under "Future Migration", one should not use the constructor

<h3>Future Migration</h3>
*
* <b>Note:</b> To simplify a future migration from this class to the standard <code>URLSearchParams</code>
* API, consuming code should follow some recommendations:
* <ul>
* <li>**do not use the constructor,** either use {@link #.fromURL UriParameters.fromURL} when the input is a full URL,
*     or use {@link #.fromQuery UriParameters.fromQuery} when the input only contains the query part of an URL
*     (e.g. <code>location.search</code>).</li>
* <li>do not use the <code>get</code> method with the second parameter <code>bAll</code>; use the <code>getAll</code>
*     method instead</li>
* <li>do not access the internal property <code>mParams</code> (you never should access internal properties of
*     UI5 classes or objects). With the predecessor of this API, access to <code>mParams</code> was often used
*     to check whether a parameter is defined at all. Using the new <code>has</code> method or checking the
*     result of <code>get</code> against <code>null</code> serves the same purpose.</li>
* </ul>

**Comment by tobiasso85** [comment]
Thanks for this feedback.

This is definitely something which needs to be adjusted.

[#fromURL](https://github.com/SAP/openui5/commit/8615e1f34e3b644ca9282f303f42c082032307d4#diff-961fca3c6147475e3d5fa4df6ba898edR231) was introduced with 1.68.0 and should be used
